import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Github, Linkedin, Mail, Heart } from 'lucide-react';
export var Footer = function () {
    var currentYear = new Date().getFullYear();
    var socialLinks = [
        { icon: Mail, href: 'mailto:kcabhirami@gmail.com', label: 'Email' },
        { icon: Linkedin, href: 'https://www.linkedin.com/in/abhirami-kc-46874917b', label: 'LinkedIn' },
        { icon: Github, href: 'https://github.com/abhiramikc', label: 'GitHub' },
    ];
    return (_jsx("footer", { className: "relative py-12 px-4 sm:px-6 lg:px-8 border-t border-white/5", children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsxs("div", { className: "grid md:grid-cols-3 gap-8 mb-8", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.6 }, viewport: { once: true }, children: [_jsx("h3", { className: "text-2xl font-bold gradient-text mb-2", children: "AC" }), _jsx("p", { className: "text-white/60 text-sm", children: "Senior Software Engineer. Building scalable web experiences." })] }), _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: 0.1 }, viewport: { once: true }, children: [_jsx("h4", { className: "font-semibold mb-4", children: "Quick Links" }), _jsx("ul", { className: "space-y-2", children: ['About', 'Experience', 'Skills', 'Projects', 'Contact'].map(function (item) { return (_jsx("li", { children: _jsx("a", { href: "#".concat(item.toLowerCase()), className: "text-white/60 hover:text-white hover:text-primary-purple transition-colors text-sm link-hover", children: item }) }, item)); }) })] }), _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: 0.2 }, viewport: { once: true }, children: [_jsx("h4", { className: "font-semibold mb-4", children: "Connect" }), _jsx("div", { className: "flex gap-4", children: socialLinks.map(function (link) {
                                        var Icon = link.icon;
                                        return (_jsx("a", { href: link.href, target: "_blank", rel: "noopener noreferrer", className: "w-10 h-10 rounded-lg glass flex items-center justify-center hover:border-primary-purple/50 hover:text-primary-purple transition-all", "aria-label": link.label, children: _jsx(Icon, { size: 20 }) }, link.label));
                                    }) })] })] }), _jsx("div", { className: "border-t border-white/5 py-8", children: _jsxs(motion.div, { initial: { opacity: 0 }, whileInView: { opacity: 1 }, transition: { duration: 0.6, delay: 0.3 }, viewport: { once: true }, className: "flex flex-col md:flex-row justify-between items-center gap-4 text-sm text-white/60", children: [_jsxs("p", { className: "flex items-center gap-2", children: ["Made with ", _jsx(Heart, { size: 16, className: "text-primary-purple" }), " by Abhirami"] }), _jsxs("p", { children: ["\u00A9 ", currentYear, " Abhirami K C. All rights reserved."] }), _jsxs("p", { children: ["Designed & Built with", ' ', _jsx("a", { href: "https://react.dev", target: "_blank", rel: "noopener noreferrer", className: "text-primary-blue hover:text-primary-purple transition-colors", children: "React" }), ' ', "&", ' ', _jsx("a", { href: "https://vitejs.dev", target: "_blank", rel: "noopener noreferrer", className: "text-primary-purple hover:text-primary-blue transition-colors", children: "Vite" })] })] }) })] }) }));
};
